INCLUDE_GUARD(GLOBAL)

IF (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    SET(CLWRAPPER_COMPILER_IS_CLANG TRUE)
ELSEIF (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    SET(CLWRAPPER_COMPILER_IS_GNU TRUE)
ENDIF ()

SET(CLWRAPPER_ROOT
    ${CMAKE_CURRENT_LIST_DIR}/..
    CACHE STRING "Root dir of the repository")
GET_FILENAME_COMPONENT(CLWRAPPER_ROOT "${CLWRAPPER_ROOT}" ABSOLUTE)
