name: Build
on: [push]

jobs:
  clwrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Load OpenCL
        run: |
          wget -qO - https://repositories.intel.com/graphics/intel-graphics.key |
            sudo apt-key add -
          sudo add-apt-repository \
            'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main'
          sudo apt-get update
          sudo apt-get install \
            intel-opencl-icd \
            intel-level-zero-gpu level-zero \
            intel-media-va-driver-non-free libmfx1
          sudo apt-get install \
            libigc-dev \
            intel-igc-cm \
            libigdfcl-dev \
            libigfxcmrt-dev \
            level-zero-dev
          sudo apt-get install ocl-icd-opencl-dev

      - name: Generate Version
        id: generate_version
        run: |
          VERSION_INCR=$(git rev-list --count HEAD | head -n 1)
          VERSION_TIME=$(date +'%Y%m%d' | head -n 1)
          VERSION_SHA=$(git rev-parse HEAD | cut -c 1-8  | head -n 1)
          VERSION_TAG="v${VERSION_INCR}.${VERSION_TIME}.${VERSION_SHA}"
          echo "Version: $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Configure CMake
        run: cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST=ON

      - name: Build CMake
        run: cmake --build build/release

      - name: Run tests
        run: ctest --test-dir build/release --output-on-failure

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ steps.generate_version.outputs.VERSION_TAG }} || true
          git push origin ${{ steps.generate_version.outputs.VERSION_TAG }} || true
          git fetch || true
